version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      JBSwzN43tObH5HiPveI3xwVfnZ4FPM8x7f+imfzdEvO95Djb2t6a4p+C++iBaJoJ5bnnyIHCWECiPLiq5tSs4OVvLH13edgUmRxQpJJaxrO6H/umdxeQztjFP/p+XmEsL4L/uQHEBofBbGFEOKGrI7x4Jr9HuclSBtohRkmj3BzDYkKf42jbrZrPVL1IStIGQE5a8mH4UFvvf6/OWzsI7LKRItLM2+WPEau96eJ/g3zB7EYyI6hAdXnJgEorRAGB5BadQgB8b5IKZ5LVdftBVn0CucpnHxTKJrNHe2lk1Ea6YswEypn++N3YgnquHBQbZsK7tknM7FkMBYFnQBcF3qWTn5/Lhy+r7teyOGE3tUPQ6kgBaIx98tEckIMFJME8QU/3pFs/upyB4i6aG+04PFpxHcfChLaRaFvXIvArmK0xs+5ZeE9q9DTxD+7EnZYCiQDg/j/z5IE2KP2u+pDMsTkKDjB5epVpzsbY3b5BylmndDhlhyQyMB334VfqjL7KtCHfkhNouNZk5XTOrhiFB6gc56tLBUQ2PwKZG/ROc+FYYy0SRCXqf9wk7TH3oxcuatmFRwq7aNmCa293pbCw7tiiP+YaCMgsP/Q5RGMd3/42W1QORAPZ7npIaO8YEyZl5yLDleQOWoniwwdKEp26njZ2dbw4rG6ya5xFcAeaoPY=
