version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      V/b24b7ICOpjnV1o6xDyXk1D+8oEGZB87B+IH8xSuo2AyDbuf1lUzb4zhJ/hP7/xzThF+QC7toAJTvl21tX+w0A+ycLZbmyFyU7qdoaqIJUwJ1VMaIUtNI6YnkSRSwoR/WbD/vOw3zbQ4zHbniYdtkt32oL3RLsRvPMqHkwMdg6CO+96L2amxkoFLn1V1tOqBi9nZhs2Q/neUgj9egArJjYl8n1mYgm071dy6N/s5Y7t43o0O0co2olId4Qbu94gs0fKGbvZjVoIpDZ239vMbyatP1lb0U6ou3k0w+ovNUhiwBEP5+kQuBhL0XF0H9keGNMY0W4UHEugGVjvU6JZjeO2pXIBig70e0T5z0LpNkxMWDC4d5vfdU0RLwHWEICk0MuY/kVdrei8dVbVzRmxYtVzeRJ47M0ixoDOpEWVzKqYjKr0vgKhyDY5okGcACISfk71/5uqvK4i1jd4KRE7l6PCk0hlPQT84SVzXefmt8yGcDkCugOYpGcuk56EW7Dss5YumP3v/eyFCBQ5QHQ6f12QNkMOJDw8G15zNrFwdEyEK8fFnx7YY9moWTCdIcQ9u2l4yGkDiXAyAIVdWPxBkMPxX3UtL8Y5U00Nqo05Fgceg1jHhZOJpOPRsNrUfUuIm5K3eeyrlELM9ep6Gp6xuj6P3VVtLbTo9gwLqShCfPw=
